package com.company.devvault.maven.service;

import com.company.devvault.analytics.entity.DownloadEvent;
import com.company.devvault.analytics.repository.DownloadEventRepository;
import com.company.devvault.artifact.entity.Artifact;
import com.company.devvault.artifact.entity.ArtifactFile;
import com.company.devvault.artifact.entity.ArtifactSource;
import com.company.devvault.artifact.entity.ArtifactVersion;
import com.company.devvault.artifact.repository.ArtifactFileRepository;
import com.company.devvault.artifact.repository.ArtifactRepository;
import com.company.devvault.artifact.repository.ArtifactVersionRepository;
import com.company.devvault.audit.service.AuditService;
import com.company.devvault.auth.entity.User;
import com.company.devvault.auth.entity.UserRole;
import com.company.devvault.auth.repository.UserRepository;
import com.company.devvault.common.exception.ApiException;
import com.company.devvault.common.util.ChecksumUtil;
import com.company.devvault.maven.parser.MavenPathParser;
import com.company.devvault.storage.ArtifactStorageService;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Base64;
import java.util.List;
import java.util.UUID;

@Service
public class MavenRepositoryService {

    private static final DateTimeFormatter METADATA_TIMESTAMP =
            DateTimeFormatter.ofPattern("yyyyMMddHHmmss").withZone(ZoneOffset.UTC);

    private final MavenPathParser pathParser;
    private final ArtifactRepository artifactRepository;
    private final ArtifactVersionRepository versionRepository;
    private final ArtifactFileRepository fileRepository;
    private final UserRepository userRepository;
    private final DownloadEventRepository downloadEventRepository;
    private final ArtifactStorageService storageService;
    private final AuditService auditService;
    private final RemoteMavenProxyService remoteProxy;

    public MavenRepositoryService(MavenPathParser pathParser, ArtifactRepository artifactRepository,
                                  ArtifactVersionRepository versionRepository, ArtifactFileRepository fileRepository,
                                  UserRepository userRepository, DownloadEventRepository downloadEventRepository,
                                  ArtifactStorageService storageService, AuditService auditService,
                                  RemoteMavenProxyService remoteProxy) {
        this.pathParser = pathParser;
        this.artifactRepository = artifactRepository;
        this.versionRepository = versionRepository;
        this.fileRepository = fileRepository;
        this.userRepository = userRepository;
        this.downloadEventRepository = downloadEventRepository;
        this.storageService = storageService;
        this.auditService = auditService;
        this.remoteProxy = remoteProxy;
    }

    public ResponseEntity<?> resolve(String repositoryPath, HttpServletRequest request) {
        MavenPathParser.ParsedPath parsed = pathParser.parse(repositoryPath);
        switch (parsed.mode) {
            case ARTIFACT_FILE:
                return resolveFile(parsed, request);
            case ARTIFACT_METADATA:
                return resolveMetadata(parsed);
            case VERSION_METADATA:
                return versionMetadata(parsed);
            default:
                throw ApiException.notFound("Unsupported repository request");
        }
    }

    /**
     * Handles PUT requests from `mvn deploy`. Maven's wagon uploads the jar,
     * pom, checksums, and maven-metadata.xml files. Checksums and metadata are
     * generated by DevVault itself, so those uploads are acknowledged and
     * ignored. Real artifact files are stored locally + registered in the DB.
     */
    @Transactional
    public ResponseEntity<?> deploy(String repositoryPath, HttpServletRequest request) {
        MavenPathParser.ParsedPath parsed;
        try {
            parsed = pathParser.parse(repositoryPath);
        } catch (ApiException ignored) {
            return ResponseEntity.ok().build();
        }
        if (parsed.mode != MavenPathParser.Mode.ARTIFACT_FILE || parsed.checksumType != null) {
            return ResponseEntity.ok().build();
        }

        User actor = resolveBasicAuthUser(request);
        if (actor == null) {
            actor = deployUser();
        }
        final User owner = actor;

        Artifact artifact = artifactRepository.findByGroupIdAndArtifactId(parsed.groupId, parsed.artifactId)
                .orElseGet(() -> {
                    Artifact created = new Artifact();
                    created.setGroupId(parsed.groupId);
                    created.setArtifactId(parsed.artifactId);
                    created.setName(humanize(parsed.artifactId));
                    created.setDescription("Deployed via mvn deploy");
                    created.setLicenseName("See pom for license details");
                    created.setOwner(owner);
                    created.setSource(ArtifactSource.INTERNAL);
                    Artifact saved = artifactRepository.save(created);
                    auditService.log("ARTIFACT_DEPLOYED", owner, "Artifact",
                            parsed.groupId + ":" + parsed.artifactId, "via mvn deploy");
                    return saved;
                });

        ArtifactVersion version = versionRepository.findByArtifactIdAndVersion(artifact.getId(), parsed.version)
                .orElseGet(() -> {
                    ArtifactVersion created = new ArtifactVersion();
                    created.setArtifact(artifact);
                    created.setVersion(parsed.version);
                    created.setReleaseNotes("Deployed via mvn deploy");
                    created.setPublishedBy(owner);
                    return versionRepository.save(created);
                });

        boolean alreadyStored = versionFiles(version).stream()
                .anyMatch(f -> f.getFileType() == parsed.fileType);
        if (alreadyStored) {
            throw ApiException.conflict("File already exists for "
                    + parsed.groupId + ":" + parsed.artifactId + ":" + parsed.version
                    + " - versions are immutable");
        }

        String relativePath = String.join("/", parsed.segments);
        try (InputStream input = request.getInputStream()) {
            storageService.storeArtifact(relativePath, input);
        } catch (IOException e) {
            throw new RuntimeException("Failed to store deployed file " + parsed.fileName, e);
        }

        ArtifactFile file = new ArtifactFile();
        file.setArtifactVersion(version);
        file.setFileName(parsed.fileName);
        file.setFileType(parsed.fileType);
        file.setStoragePath(relativePath);
        file.setFileSize(request.getContentLengthLong());
        try (InputStream input = Files.newInputStream(storageService.resolvePath(relativePath))) {
            file.setChecksum(ChecksumUtil.sha256(input));
        } catch (IOException e) {
            throw new RuntimeException("Failed to checksum deployed file " + parsed.fileName, e);
        }
        fileRepository.save(file);
        artifact.setUpdatedAt(Instant.now());
        artifactRepository.save(artifact);
        auditService.log("VERSION_DEPLOYED", actor, "ArtifactVersion",
                parsed.groupId + ":" + parsed.artifactId + ":" + parsed.version, "via mvn deploy");
        return ResponseEntity.ok().build();
    }

    @Transactional
    public ResponseEntity<?> resolveFile(MavenPathParser.ParsedPath parsed, HttpServletRequest request) {
        Artifact artifact = artifactRepository.findByGroupIdAndArtifactId(parsed.groupId, parsed.artifactId)
                .orElse(null);
        if (artifact == null) {
            return proxyFile(parsed, request);
        }
        ArtifactVersion version = versionRepository.findByArtifactIdAndVersion(artifact.getId(), parsed.version)
                .orElse(null);
        if (version == null) {
            return proxyFile(parsed, request);
        }
        ArtifactFile file = versionFiles(version).stream()
                .filter(f -> f.getFileType() == parsed.fileType)
                .findFirst()
                .orElse(null);
        if (file == null) {
            return proxyFile(parsed, request);
        }

        if (parsed.checksumType != null) {
            return checksumResponse(parsed, file);
        }

        Path path = storageService.resolvePath(file.getStoragePath());
        Resource resource = new FileSystemResource(path);

        User user = resolveBasicAuthUser(request);
        recordDownload(artifact, version, file, user, request);
        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_LENGTH, String.valueOf(file.getFileSize()))
                .contentType(MediaType.parseMediaType(contentType(file.getFileName())))
                .body(resource);
    }

    private ResponseEntity<?> proxyFile(MavenPathParser.ParsedPath parsed, HttpServletRequest request) {
        if (!remoteProxy.enabled()) {
            throw ApiException.notFound("Artifact not found: " + parsed.groupId + ":" + parsed.artifactId);
        }
        String baseName = stripChecksumSuffix(parsed.fileName);
        String relativePath = String.join("/", parsed.segments);
        if (!baseName.equals(parsed.fileName)) {
            relativePath = relativePath.substring(0, relativePath.length() - parsed.fileName.length()) + baseName;
        }
        byte[] bytes = remoteProxy.fetch(relativePath);
        if (bytes == null) {
            throw ApiException.notFound("Artifact not found locally or on remote repository: "
                    + parsed.groupId + ":" + parsed.artifactId + ":" + parsed.version);
        }
        ArtifactFile file = remoteProxy.importFile(parsed.groupId, parsed.artifactId, parsed.version,
                baseName, parsed.fileType, bytes);

        if (parsed.checksumType != null) {
            return checksumResponse(parsed, file);
        }

        Artifact artifact = file.getArtifactVersion().getArtifact();
        ArtifactVersion version = file.getArtifactVersion();
        Path path = storageService.resolvePath(file.getStoragePath());
        Resource resource = new FileSystemResource(path);
        User user = resolveBasicAuthUser(request);
        recordDownload(artifact, version, file, user, request);
        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_LENGTH, String.valueOf(file.getFileSize()))
                .contentType(MediaType.parseMediaType(contentType(file.getFileName())))
                .body(resource);
    }

    private String stripChecksumSuffix(String fileName) {
        if (fileName.endsWith(".sha1")) {
            return fileName.substring(0, fileName.length() - 5);
        }
        if (fileName.endsWith(".sha256")) {
            return fileName.substring(0, fileName.length() - 7);
        }
        if (fileName.endsWith(".md5")) {
            return fileName.substring(0, fileName.length() - 4);
        }
        return fileName;
    }

    private ResponseEntity<String> resolveMetadata(MavenPathParser.ParsedPath parsed) {
        String[] segments = parsed.segments;
        if (segments.length >= 3) {
            MavenPathParser.ParsedPath artifactLevel = pathParser.artifactMetadataPath(segments);
            try {
                return artifactMetadata(artifactLevel);
            } catch (ApiException ignored) {
                if (segments.length >= 4) {
                    try {
                        return versionMetadata(pathParser.versionMetadataPath(segments));
                    } catch (ApiException ignored2) {
                        // fall through to remote proxy
                    }
                }
            }
        }
        if (remoteProxy.enabled()) {
            byte[] remote = remoteProxy.fetch(String.join("/", segments));
            if (remote != null) {
                return ResponseEntity.ok()
                        .contentType(MediaType.parseMediaType("application/xml"))
                        .body(new String(remote, java.nio.charset.StandardCharsets.UTF_8));
            }
        }
        throw ApiException.notFound("Artifact not found: " + String.join(".", segments));
    }

    public ResponseEntity<String> artifactMetadata(MavenPathParser.ParsedPath parsed) {
        Artifact artifact = artifactRepository.findByGroupIdAndArtifactId(parsed.groupId, parsed.artifactId)
                .orElseThrow(() -> ApiException.notFound("Artifact not found: " + parsed.groupId + ":" + parsed.artifactId));
        List<ArtifactVersion> versions = versionRepository.findByArtifactIdOrderByCreatedAtDesc(artifact.getId());
        String latest = versions.isEmpty() ? null : versions.get(0).getVersion();
        StringBuilder xml = new StringBuilder();
        xml.append("<metadata>");
        xml.append("<groupId>").append(escape(parsed.groupId)).append("</groupId>");
        xml.append("<artifactId>").append(escape(parsed.artifactId)).append("</artifactId>");
        xml.append("<versioning>");
        if (latest != null) {
            xml.append("<latest>").append(escape(latest)).append("</latest>");
            xml.append("<release>").append(escape(latest)).append("</release>");
        }
        xml.append("<versions>");
        for (ArtifactVersion v : versions) {
            xml.append("<version>").append(escape(v.getVersion())).append("</version>");
        }
        xml.append("</versions>");
        xml.append("<lastUpdated>").append(METADATA_TIMESTAMP.format(Instant.now())).append("</lastUpdated>");
        xml.append("</versioning>");
        xml.append("</metadata>");
        return xmlResponse(xml.toString());
    }

    public ResponseEntity<String> versionMetadata(MavenPathParser.ParsedPath parsed) {
        artifactRepository.findByGroupIdAndArtifactId(parsed.groupId, parsed.artifactId)
                .orElseThrow(() -> ApiException.notFound("Artifact not found: " + parsed.groupId + ":" + parsed.artifactId));
        StringBuilder xml = new StringBuilder();
        xml.append("<metadata>");
        xml.append("<groupId>").append(escape(parsed.groupId)).append("</groupId>");
        xml.append("<artifactId>").append(escape(parsed.artifactId)).append("</artifactId>");
        xml.append("<version>").append(escape(parsed.version)).append("</version>");
        xml.append("<versioning>");
        xml.append("<lastUpdated>").append(METADATA_TIMESTAMP.format(Instant.now())).append("</lastUpdated>");
        xml.append("</versioning>");
        xml.append("</metadata>");
        return xmlResponse(xml.toString());
    }

    private ResponseEntity<String> checksumResponse(MavenPathParser.ParsedPath parsed, ArtifactFile file) {
        Path path = storageService.resolvePath(file.getStoragePath());
        String checksum;
        try (InputStream input = Files.newInputStream(path)) {
            switch (parsed.checksumType) {
                case "SHA1":
                    checksum = ChecksumUtil.sha1(input);
                    break;
                case "SHA256":
                    checksum = ChecksumUtil.sha256(input);
                    break;
                case "MD5":
                    checksum = ChecksumUtil.md5(input);
                    break;
                default:
                    throw ApiException.notFound("Unsupported checksum type: " + parsed.checksumType);
            }
        } catch (IOException e) {
            throw new RuntimeException("Failed to read artifact for checksum", e);
        }
        return ResponseEntity.ok()
                .contentType(MediaType.TEXT_PLAIN)
                .body(checksum);
    }

    private ResponseEntity<String> xmlResponse(String xml) {
        return ResponseEntity.ok()
                .contentType(MediaType.parseMediaType("application/xml"))
                .body(xml);
    }

    private List<ArtifactFile> versionFiles(ArtifactVersion version) {
        return fileRepository.findByArtifactVersionId(version.getId());
    }

    private void recordDownload(Artifact artifact, ArtifactVersion version, ArtifactFile file,
                                User user, HttpServletRequest request) {
        artifact.setDownloadCount(artifact.getDownloadCount() + 1);
        version.setDownloadCount(version.getDownloadCount() + 1);
        artifactRepository.save(artifact);
        versionRepository.save(version);
        DownloadEvent event = new DownloadEvent();
        event.setArtifact(artifact);
        event.setArtifactVersion(version);
        event.setArtifactFile(file);
        event.setUser(user);
        event.setIpAddress(request.getRemoteAddr());
        String userAgent = request.getHeader("User-Agent");
        event.setUserAgent(userAgent != null && userAgent.length() > 500 ? userAgent.substring(0, 500) : userAgent);
        downloadEventRepository.save(event);
        if (user != null) {
            auditService.log("ARTIFACT_DOWNLOADED", user, "ArtifactFile",
                    artifact.getGroupId() + ":" + artifact.getArtifactId() + ":" + version.getVersion(), "via Maven");
        }
    }

    private User resolveBasicAuthUser(HttpServletRequest request) {
        String header = request.getHeader(HttpHeaders.AUTHORIZATION);
        if (header != null && header.startsWith("Basic ")) {
            try {
                String decoded = new String(Base64.getDecoder().decode(header.substring(6)));
                String[] parts = decoded.split(":", 2);
                if (parts.length == 2) {
                    return userRepository.findByEmail(parts[0]).orElse(null);
                }
            } catch (IllegalArgumentException ignored) {
                // Invalid base64 - ignore
            }
        }
        return null;
    }

    private User deployUser() {
        return userRepository.findByEmail("maven-deploy@devvault.local").orElseGet(() -> {
            User user = new User();
            user.setEmail("maven-deploy@devvault.local");
            user.setName("Maven Deploy");
            user.setPasswordHash(new org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder()
                    .encode(UUID.randomUUID().toString()));
            user.setRole(UserRole.DEVELOPER);
            return userRepository.save(user);
        });
    }

    private String humanize(String artifactId) {
        String readable = artifactId.replace('-', ' ').replace('_', ' ');
        String[] words = readable.split("\\s+");
        StringBuilder builder = new StringBuilder();
        for (String word : words) {
            if (!word.isEmpty()) {
                if (builder.length() > 0) {
                    builder.append(' ');
                }
                builder.append(Character.toUpperCase(word.charAt(0))).append(word.substring(1));
            }
        }
        return builder.length() > 0 ? builder.toString() : artifactId;
    }

    private String contentType(String fileName) {
        if (fileName.endsWith(".jar")) {
            return "application/java-archive";
        }
        if (fileName.endsWith(".pom") || fileName.endsWith(".xml")) {
            return "application/xml";
        }
        return "application/octet-stream";
    }

    private String escape(String value) {
        return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}